### ISSUE TITLE
Default value of Enumerated types are stored as strings even when numeric_enums is set to true

### ISSUE THREAD

**Issue by navetal39** [eerimoq/asn1tools#105]
Take for example this file:
```
Example DEFINITIONS AUTOMATIC TAGS ::=

BEGIN

ExampleSequence ::=		SEQUENCE {
	integer1				INTEGER (1..4),
	integer2				INTEGER (1..4),
	boolean					BOOLEAN,
	integer3				INTEGER (0..7),
	enumeratedWithDefault	ExampleEnum		DEFAULT a3
}

ExampleEnum ::=	ENUMERATED {a0, a1, a2, a3, a4, a5, a6, a7}

END
```
Running this code:
```
import asn1tools
c = asn1tools.compile_files('./example.asn', numeric_enums=True)

d0= c.decode("ExampleSequence", b'0\x0f\x80\x01\x03\x81\x01\x02\x82\x01\xff\x83\x01\x03\x84\x01\x00')
print("d0:", d0)
d1= c.decode("ExampleSequence", b'0\x0c\x80\x01\x03\x81\x01\x02\x82\x01\xff\x83\x01\x03')
print("d1:", d1)

e0= c.encode("ExampleSequence", d0)
print("e0:", e0)
e1= c.encode("ExampleSequence", d1)
print("e1:", e1)
```

leads to the following result:
```
d0: {'integer1': 3, 'integer2': 2, 'boolean': True, 'integer3': 3, 'enumeratedWithDefault': 0}
d1: {'integer1': 3, 'integer2': 2, 'boolean': True, 'integer3': 3, 'enumeratedWithDefault': 'a3'}
e0: bytearray(b'0\x0f\x80\x01\x03\x81\x01\x02\x82\x01\xff\x83\x01\x03\x84\x01\x00')
Traceback (most recent call last):
  File "./example.py", line 11, in <module>
    e1= c.encode("ExampleSequence", d1)
  File "/home/navetal/Desktop/asn1tools-master/asn1tools/compiler.py", line 133, in encode
    type_.check_types(data)
  File "/home/navetal/Desktop/asn1tools-master/asn1tools/codecs/compiler.py", line 96, in check_types
    return self.type_checker.encode(data)
  File "/home/navetal/Desktop/asn1tools-master/asn1tools/codecs/type_checker.py", line 296, in encode
    self._type.encode(data)
  File "/home/navetal/Desktop/asn1tools-master/asn1tools/codecs/type_checker.py", line 148, in encode
    member.encode(data[name])
  File "/home/navetal/Desktop/asn1tools-master/asn1tools/codecs/type_checker.py", line 177, in encode
    self.encode_integer(data)
  File "/home/navetal/Desktop/asn1tools-master/asn1tools/codecs/type_checker.py", line 184, in encode_integer
    raise EncodeError(
asn1tools.codecs.EncodeError: enumeratedWithDefault: Expected data of type int, but got a3.
```
Also occurs when using PER:
```
import asn1tools
c = asn1tools.compile_files('./example.asn',  'per', numeric_enums=True)

d0= c.decode("ExampleSequence", bytearray.fromhex('cd80'))
print("d0:", d0)
d1= c.decode("ExampleSequence", bytearray.fromhex('4d80'))
print("d1:", d1)

e0= c.encode("ExampleSequence", d0)
print("e0:", e0)
e1= c.encode("ExampleSequence", d1)
print("e1:", e1)
```
leads to:
```
d0: {'integer1': 3, 'integer2': 2, 'boolean': True, 'integer3': 3, 'enumeratedWithDefault': 0}
d1: {'integer1': 3, 'integer2': 2, 'boolean': True, 'integer3': 3, 'enumeratedWithDefault': 'a3'}
e0: bytearray(b'\xcd\x80')
Traceback (most recent call last):
  File "./example.py", line 10, in <module>
    e1= c.encode("ExampleSequence", d1)
  File "/home/navetal/Desktop/asn1tools-master/asn1tools/compiler.py", line 133, in encode
    type_.check_types(data)
  File "/home/navetal/Desktop/asn1tools-master/asn1tools/codecs/compiler.py", line 96, in check_types
    return self.type_checker.encode(data)
  File "/home/navetal/Desktop/asn1tools-master/asn1tools/codecs/type_checker.py", line 296, in encode
    self._type.encode(data)
  File "/home/navetal/Desktop/asn1tools-master/asn1tools/codecs/type_checker.py", line 148, in encode
    member.encode(data[name])
  File "/home/navetal/Desktop/asn1tools-master/asn1tools/codecs/type_checker.py", line 177, in encode
    self.encode_integer(data)
  File "/home/navetal/Desktop/asn1tools-master/asn1tools/codecs/type_checker.py", line 184, in encode_integer
    raise EncodeError(
asn1tools.codecs.EncodeError: enumeratedWithDefault: Expected data of type int, but got a3.

```

**Comment by eerimoq** [comment]
Hi, thanks for the bug report. I don't have time to fix it. Feel free to help out.
