### ISSUE TITLE
Generate C source: Unsupported type 'BIT STRING'

### ISSUE THREAD

**Issue by mstmob** [eerimoq/asn1tools#149]
Hi
I am trying to generate c source files from the 3GPP RRC ASN.1 spec (i.e. rrc_14_4_0.asn in the test files).
I slightly modified the spec so that there aren`t any ExtensionAdditions (The checker doesn`t support it and I don`t need them.).

I'm using the following command with asn1tools v0.161.0:
```
asn1tools generate_c_source --codec uper --namespace uper ./rrc_14_4_0.asn
```
Unfortunately I get this error:
```
error: EUTRA-RRC-Definitions.CSG-Identity: Unsupported type 'BIT STRING'.
```
The `BIT STRING` type seems to be generally implemented however some functionality is missing in the c source code generation. 

The debug log:
```
Traceback (most recent call last):
  File "asn1tools", line 33, in <module> sys.exit(load_entry_point('asn1tools==0.161.0', 'console_scripts', 'asn1tools')())
  File "asn1tools/__init__.py", line 433, in _main
  File "asn1tools/__init__.py", line 278, in _do_generate_c_source
  File "asn1tools/source/c/__init__.py", line 394, in generate
  File "asn1tools/source/c/uper.py", line 618, in generate
  File "asn1tools/source/c/utils.py", line 696, in generate
  File "asn1tools/source/c/utils.py", line 633, in generate_type_declaration
  File "asn1tools/source/c/uper.py", line 96, in generate_type_declaration_process

```

**Comment by eerimoq** [comment]
Will have a look in a few days.

**Comment by mstmob** [comment]
Thank you!
My PR works for some first experiments.
And as I am understanding the internals of asn1tools I think I can workaround most issues with the RRC spec for my use case...

**Comment by Futsch1** [comment]
> Will have a look in a few days.

I had a look already and merged it.
