### ISSUE TITLE
PER cannot decode CHOICE

### ISSUE THREAD

**Issue by matspetter** [eerimoq/asn1tools#16]
The PER decoder does not seem to be able to handle CHOICE. Encoding goes fine.
I have this toy-specification called asn1.asn :
```
Foo DEFINITIONS ::= BEGIN
    MyChoice ::= CHOICE {
            c1   NULL,
            c2   INTEGER,
            c3   INTEGER
    }
END
```

My test code looks like:
```
import asn1tools
foo = asn1tools.compile_files('asn1.asn', codec='per')
encoded = foo.encode('MyChoice', ('c2',5)) # this goes fine
decoded = foo.decode('MyChoice',encoded) # this fails in per.py
```

Error trace:
```
Traceback (most recent call last):
  File "/Users/mats/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/173.4674.37/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1668, in <module>
    main()
  File "/Users/mats/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/173.4674.37/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Users/mats/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/173.4674.37/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Projects/asn1test/mymain.py", line 115, in <module>
    decoded = foo.decode('MyChoice',encoded)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/asn1tools/compiler.py", line 116, in decode
    return self._types[name].decode(data)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/asn1tools/codecs/per.py", line 820, in decode
    return self._type.decode(decoder)
TypeError: decode() takes exactly 3 arguments (2 given)
```

**Comment by eerimoq** [comment]
I'll have a look at it. The PER codec lacks lots of functionality, but it shouldn't be too hard or time consuming to implement most of it.

**Comment by eerimoq** [comment]
Your example works with asn1tools 0.68.0. It's available on PyPI.

Feel free to create new issues if you find more bugs/missing functionality, and I'll prioritize implementing them.

**Comment by URockMan** [comment]
Can you please confirm if you have updated CHOICE Fix for uper codec as well ?

**Comment by eerimoq** [comment]
The fix in this issue was already in place in UPER.
