### ISSUE TITLE
oer c code generation fails when addition contains a sequence with enums (type error)

### ISSUE THREAD

**Issue by EuchnerDev** [eerimoq/asn1tools#168]
When generating oer c-code from an asn1 specification containing a sequence with enums inside an addition, the generation fails with the following error message:
**`'<' not supported between instance of 'str' and 'int'. <class TypeError>`**

asn1tools version: 0.166.0

Example asn1 specification:
```
Auto DEFINITIONS AUTOMATIC TAGS ::=
BEGIN

UINT8  ::= INTEGER(0..255)

ExampleEnum ::= ENUMERATED
{
    v (86),
    t (84),
    p (80)
}

ExampleSequenceWithEnum ::= SEQUENCE
{
    enumeratedSequence  ExampleEnum,
    uint8Sequence       UINT8
}


ExampleSequenceFinal ::= SEQUENCE
{
    uint8                    UINT8,
    ...,
    additionWithSequence     SEQUENCE (SIZE(1..32)) OF ExampleSequenceWithEnum OPTIONAL,
    ...
}

END
```

compiler output:
```
Traceback (most recent call last):
  File "asn1tools\source\c\__init__.py", line 390, in generate
    structs, declarations, helpers, definitions = oer.generate(
  File "asn1tools\source\c\oer.py", line 1112, in generate
    return _Generator(namespace).generate(compiled)
  File "asn1tools\source\c\utils.py", line 703, in generate
    definition_inner = self.generate_definition_inner(compiled_type)
  File "asn1tools\source\c\utils.py", line 667, in generate_definition_inner
    encode_lines, decode_lines = self.generate_definition_inner_process(
  File "asn1tools\source\c\oer.py", line 1073, in generate_definition_inner_process
    return self.format_sequence_inner(type_, checker)
  File "asn1tools\source\c\oer.py", line 435, in format_sequence_inner
    self.format_sequence_additions(type_, checker))
  File "asn1tools\source\c\oer.py", line 576, in format_sequence_additions
    encoded_lengths = self.get_encoded_type_lengths(addition, member_checker)
  File "asn1tools\source\c\oer.py", line 189, in get_encoded_type_lengths
    return self.get_encoded_sequence_of_lengths(type_, checker)
  File "asn1tools\source\c\oer.py", line 1026, in get_encoded_sequence_of_lengths
    inner_lengths = self.get_encoded_type_lengths(type_.element_type,
  File "asn1tools\source\c\oer.py", line 185, in get_encoded_type_lengths
    return self.get_encoded_sequence_lengths(type_, checker)
  File "asn1tools\source\c\oer.py", line 634, in get_encoded_sequence_lengths
    lengths.extend(self.get_encoded_type_lengths(member, checker))
  File "asn1tools\source\c\oer.py", line 175, in get_encoded_type_lengths
    return self.get_encoded_integer_lengths(checker)
  File "asn1tools\source\c\oer.py", line 287, in get_encoded_integer_lengths
    return [self.type_length(checker.minimum, checker.maximum) // 8]
  File "asn1tools\source\c\utils.py", line 193, in type_length
    if minimum < -9223372036854775808:
TypeError: '<' not supported between instances of 'str' and 'int'
```

Do you have a tip for me how to fix it, please?
Thanks in advance!

**Comment by Futsch1** [comment]
I will have a look at it

**Comment by EuchnerDev** [comment]
Thank you very much for the very quick investigation and fix!
