### ISSUE TITLE
EncodeError("expected tuple, but got '{}'".format(data))

### ISSUE THREAD

**Issue by URockMan** [eerimoq/asn1tools#17]
For some reason, we are facing below issue earlier it was working fine. 

Question to encode: {'aTCmessageheader': {'timestamp': {'timehours': 10, 'timeminutes': 57, 'timeseconds': 8}, 'msgreferencenumber': 1, 'msgidentificationnumber': 1}, 'aTCuplinkmsgelementid': {'uM163ICAOfacilitydesignationTp4table': {'tp4table': 'labelA', 'iCAOfacilitydesignation': 'GDTA'}}}

Please let me know if you need asn file. I will share via email
Traceback (most recent call last):
  File "fans_cr1_messages_encode.py", line 103, in <module>
    encoded = foo.encode('ATCuplinkmessage', atcuplinkmessage)
  File "/usr/lib/python2.7/site-packages/asn1tools/compiler.py", line 100, in encode
    return self._types[name].encode(data, **kwargs)
  File "/usr/lib/python2.7/site-packages/asn1tools/codecs/uper.py", line 1246, in encode
    self._type.encode(data, encoder)
  File "/usr/lib/python2.7/site-packages/asn1tools/codecs/uper.py", line 471, in encode
    self.encode_root(data, encoder)
  File "/usr/lib/python2.7/site-packages/asn1tools/codecs/uper.py", line 483, in encode_root
    self.encode_member(member, data, encoder)
  File "/usr/lib/python2.7/site-packages/asn1tools/codecs/uper.py", line 539, in encode_member
    member.encode(data[name], encoder)
  File "/usr/lib/python2.7/site-packages/asn1tools/codecs/uper.py", line 1015, in encode
    raise EncodeError("expected tuple, but got '{}'".format(data))
asn1tools.codecs.EncodeError: expected tuple, but got '{'uM163ICAOfacilitydesignationTp4table': {'tp4table': 'labelA', 'iCAOfacilitydesignation': 'GDTA'}}'

**Comment by eerimoq** [comment]
I changed the Python type of CHOICE from a dict to a tuple. 

Try this instead: ('uM163ICAOfacilitydesignationTp4table', {'tp4table': 'labelA', 'iCAOfacilitydesignation': 'GDTA'})
