### ISSUE TITLE
Support for SAE J2735?

### ISSUE THREAD

**Issue by anoopjb** [eerimoq/asn1tools#18]
I am trying to compile ASN.1 Schema provided by SAE J2735.
I am getting below error:

```
>>>import asn1tools
 >>>foo = asn1tools.compile_files("J2735.ASN")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/asn1tools/compiler.py", line 243, in compile_files
    return compile_dict(parse_files(filenames),
  File "/usr/lib/python2.7/site-packages/asn1tools/parser.py", line 1707, in parse_files
    return parse_string(string)
  File "/usr/lib/python2.7/site-packages/asn1tools/parser.py", line 1684, in parse_string
    e.msg))
asn1tools.parser.ParseError: Invalid ASN.1 syntax at line 140, column 36: 'TestExtension >!<{{REGION.Reg-TestMessage}} OPTIONAL,': Expected "}".
```

Snippet from ASN.1

```
TestMessage::= SEQUENCE {
   -- Part I, Sent at all times with each message
   coreData      TestcoreData,

   -- Part II Content
   partII        SEQUENCE (SIZE(1..8)) OF
                 PartIIcontent {{ partIIExtension }} OPTIONAL,

   regional      SEQUENCE (SIZE(1..4)) OF
                TestExtension {{REGION.Reg-TestMessage}} OPTIONAL,
   ...
   }

```

**Comment by eerimoq** [comment]
I have no intrest in implementing support for object sets (CLASS keyword, etc.) as I don't use these constructs myself. Feel free to implement it. =)

**Comment by psonis** [comment]
Any update on this? Is there any good alternative to batch encode such messages (SPATEM)?
