### ISSUE TITLE
Cannot import name WordCompleter

### ISSUE THREAD

**Issue by amlamarra** [eerimoq/asn1tools#30]
Hello, I just installed asn1tools but I'm unable to import the module:

```
# pip install asn1tools
Collecting asn1tools
  Downloading https://files.pythonhosted.org/packages/36/93/a3c1e9fb9ff06299d6cd895fc60b8774831b21c1df4161dab0b3c794c34f/asn1tools-0.124.0-py2.py3-none-any.whl (75kB)
    100% |████████████████████████████████| 81kB 309kB/s 
Requirement already satisfied: prompt-toolkit in /usr/lib/python2.7/dist-packages (from asn1tools)
Requirement already satisfied: pyparsing>=2.2.0 in /usr/lib/python2.7/dist-packages (from asn1tools)
Collecting bitstruct (from asn1tools)
  Downloading https://files.pythonhosted.org/packages/46/6f/0bcaa2c1eaf8fb7f44d5ca43d35dc677a660d3ba9050392f0df782e29e71/bitstruct-4.0.0-py2.py3-none-any.whl
Installing collected packages: bitstruct, asn1tools
Successfully installed asn1tools-0.124.0 bitstruct-4.0.0

# python
Python 2.7.15+ (default, Aug 31 2018, 11:56:52) 
[GCC 8.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import asn1tools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/asn1tools/__init__.py", line 14, in <module>
    from prompt_toolkit.completion import WordCompleter
ImportError: cannot import name WordCompleter
```

**Comment by eerimoq** [comment]
Try `pip install -U asn1tools`. I have prompt_toolkit 2.0.4 installed.

**Comment by amlamarra** [comment]
> Try `pip install -U asn1tools`. I have prompt_toolkit 2.0.4 installed.

Yup, that did it for me. Thanks!
