### ISSUE TITLE
compile ieee1609_2.asn fail:  Value 'unknown' not found in module 'IEEE1609dot2BaseTypes' 

### ISSUE THREAD

**Issue by DmitriKh** [eerimoq/asn1tools#32]
Hello Folks,
I tried to compile ieee1609_2.asn listed in asn1tools/tree/master/tests/files/ieee.
Got error: Value 'unknown' not found in module 'IEEE1609dot2BaseTypes' 

<pre>
import asn1tools
oer = asn1tools.compile_files('ieee1609_2.asn', 'oer')
</pre>

<pre>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\asn1tools\compiler.py", line 331, in compile_files
    any_defined_by_choices)
  File "C:\Python27\lib\site-packages\asn1tools\compiler.py", line 275, in compile_dict
    return Specification(codec.compile_dict(specification),
  File "C:\Python27\lib\site-packages\asn1tools\codecs\oer.py", line 1354, in compile_dict
    return Compiler(specification).process()
  File "C:\Python27\lib\site-packages\asn1tools\codecs\compiler.py", line 122, in process
    module_name)
  File "C:\Python27\lib\site-packages\asn1tools\codecs\oer.py", line 1180, in process_type
    module_name)
  File "C:\Python27\lib\site-packages\asn1tools\codecs\oer.py", line 1306, in compile_type
    module_name)
  File "C:\Python27\lib\site-packages\asn1tools\codecs\compiler.py", line 682, in set_compiled_restricted_to
    module_name))
  File "C:\Python27\lib\site-packages\asn1tools\codecs\compiler.py", line 561, in get_restricted_to_range
    minimum = self.lookup_value(minimum, module_name)[0]['value']
  File "C:\Python27\lib\site-packages\asn1tools\codecs\compiler.py", line 630, in lookup_value
    return self.lookup_in_modules('values', 'value', value_name, module_name)
  File "C:\Python27\lib\site-packages\asn1tools\codecs\compiler.py", line 622, in lookup_in_modules
    module_name))
asn1tools.errors.CompileError: Value 'unknown' not found in module 'IEEE1609dot2BaseTypes'
</pre>

**Comment by eerimoq** [comment]
See https://github.com/eerimoq/asn1tools/issues/27 for a workaround.
