### ISSUE TITLE
Uper encoding failed with 'Odd-length string error"

### ISSUE THREAD

**Issue by sudhakarnaidu** [eerimoq/asn1tools#44]
In our .asn file has a field defined ids SEQUENCE SIZE(1..10) OF UTF8String (SIZE(1..32))

but when we provide input as "ids:[]" it throws an error saying "Odd-length string" instead of expecting sequence size should be > 1

**Comment by eerimoq** [comment]
Please provide a minimal script that can be used to reproduce the error. It greatly speeds up debugging as is eliminates the need of guessing.

**Comment by eerimoq** [comment]
Okay, so it was easy to reproduce:

``` python
>>> import asn1tools
>>> foo = asn1tools.compile_string('A DEFINITIONS AUTOMATIC TAGS ::= BEGIN A ::= SEQUENCE SIZE (1..10) OF NULL END', 'uper')
>>> foo.encode('A', [])
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    foo.encode('A', [])
  File "/home/erik/workspace/asn1tools/asn1tools/compiler.py", line 138, in encode
    return type_.encode(data, **kwargs)
  File "/home/erik/workspace/asn1tools/asn1tools/codecs/uper.py", line 283, in encode
    return encoder.as_bytearray()
  File "/home/erik/workspace/asn1tools/asn1tools/codecs/per.py", line 247, in as_bytearray
    return bytearray(binascii.unhexlify(value))
binascii.Error: Odd-length string
```

With `encode(..., check_constraints=True)` the error is as expected:

``` python
>>> foo.encode('A', [], check_constraints=True)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    foo.encode('A', [], check_constraints=True)
  File "/home/erik/workspace/asn1tools/asn1tools/compiler.py", line 136, in encode
    type_.check_constraints(data)
  File "/home/erik/workspace/asn1tools/asn1tools/codecs/compiler.py", line 94, in check_constraints
    return self.constraints_checker.encode(data)
  File "/home/erik/workspace/asn1tools/asn1tools/codecs/constraints_checker.py", line 342, in encode
    self._type.encode(data)
  File "/home/erik/workspace/asn1tools/asn1tools/codecs/constraints_checker.py", line 247, in encode
    length))
asn1tools.codecs.ConstraintsError: Expected a list of between 1 and 10 elements, but got 0.
>>>
```

The codec design requires `check_constraints=True` to give proper error messages. That's by design. The constraints checker is disabled by default as it was recently added and probably needs more testing before being enabled by default. Also, enabling it obviously slows down encoding slightly, which shouldn't be a problem in most applications. Better error messages and constraints checks is helpful for the user debugging her application.

**Comment by sudhakarnaidu** [comment]
Thank you so much for the information. I will enable "check_constraints" parameter
