### ISSUE TITLE
UPER decode error when using REAL and extension marker

### ISSUE THREAD

**Issue by jnsptrsn** [eerimoq/asn1tools#45]
I believe I found a bug when decoding a structure containing a REAL and extension marker using UPER:
```Python
Python 2.7.14 (default, Oct 31 2017, 21:12:13)
[GCC 6.4.0] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import asn1tools
>>> asn = """
... Test DEFINITIONS ::= BEGIN
...     Test ::= SEQUENCE
...     {
...         value   REAL,
...         ...
...     }
... END
... """
>>> uper = asn1tools.compile_string(asn, codec = 'uper')
>>> encoded = uper.encode("Test", {'value': 120})
>>> uper.decode("Test", encoded)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/asn1tools/compiler.py", line 163, in decode
    decoded = type_.decode(data)
  File "/usr/lib/python2.7/site-packages/asn1tools/codecs/uper.py", line 288, in decode
    return self._type.decode(decoder)
  File "/usr/lib/python2.7/site-packages/asn1tools/codecs/per.py", line 816, in decode
    decoded = self.decode_root(decoder)
  File "/usr/lib/python2.7/site-packages/asn1tools/codecs/per.py", line 832, in decode_root
    value = member.decode(decoder)
  File "/usr/lib/python2.7/site-packages/asn1tools/codecs/per.py", line 1095, in decode
    return decode_real(decoder.read_bytes_aligned(length))
  File "/usr/lib/python2.7/site-packages/asn1tools/codecs/ber.py", line 313, in decode_real
    decoded = decode_real_decimal(data)
  File "/usr/lib/python2.7/site-packages/asn1tools/codecs/ber.py", line 299, in decode_real_decimal
    return float(data[1:])
ValueError: could not convert string to float: ▒▒
```

**Comment by eerimoq** [comment]
The UPER and PER REAL encoding and decoding functions did not align the data correctly. I implemented a correction in version 0.137.1, available on PyPI!

Close the issue if it works.

**Comment by jnsptrsn** [comment]
Works! Thanks a lot for you work with this project.

**Comment by eerimoq** [comment]
No problem, I'm glad you like it! =)
