### ISSUE TITLE
Encoding fails for INTEGER with length more than 614 digits

### ISSUE THREAD

**Issue by prateeknischal** [eerimoq/asn1tools#61]
This issue is related with #5 but with the `INTEGER` type. The library is not able to encode integers with length greater than 614 digits. While looking at the code, it seems that the `Length` in the DER encoding is not encoded properly if it exceeds 127, as with the issue mentioned with `OCTET STRING`.

How to reproduce:
I am trying to encode a RSA public key. To get a sample modulus,
```bash
echo '' | openssl s_client -connect docs.microsoft.com:443 | openssl x509 -noout -pubkey | openssl asn1parse -inform PEM -strparse 19
```
Suppose, at the time, it gives the modulus:
```bash
    0:d=0  hl=4 l= 266 cons: SEQUENCE          
    4:d=1  hl=4 l= 257 prim: INTEGER           :CBD6513415377984BDC1242380B5C620F5C88402B03C00D1D62FA682479768B0917C606A82C7FD1D038A2D0EB3ECEDD250F7EC7F4637E4B1DB8081925EC053C98BC2C86D031F330F081E92D5F160179346B0E8A5EF557292D6675CEADE6317D08E4241E1AEAF5DA9DA8C579625F83F82DCF0CBB3F253ED9EDCCA9B3F2C433E33CCD725AB5AB5F8623630F0E8968F32F562A7B37948BF6D6D54BC20068A353306F557573E76965332BE3A547CB500534C616869AD011E8E74A823A26C104CAC93F637AA526D2D1CB095E1875540653FB3E01E3ACF31ED89E3A021EDFB7561DE1CA9D111EA63E4A456730F18910116EDDB23C9AD5A166505647D31688491F5E4ED
  265:d=1  hl=2 l=   3 prim: INTEGER           :010001
```
Using it encode:
```python
import asn1tools
from base64 import b64encode

enc = asn1tools.compile_string('''
Foo DEFINITIONS ::= BEGIN

RSAPublicKey ::= SEQUENCE {
	modulus     	INTEGER,
	publicExponent 	INTEGER
}

END
''')
x=0xCBD6513415377984BDC1242380B5C620F5C88402B03C00D1D62FA682479768B0917C606A82C7FD1D038A2D0EB3ECEDD250F7EC7F4637E4B1DB8081925EC053C98BC2C86D031F330F081E92D5F160179346B0E8A5EF557292D6675CEADE6317D08E4241E1AEAF5DA9DA8C579625F83F82DCF0CBB3F253ED9EDCCA9B3F2C433E33CCD725AB5AB5F8623630F0E8968F32F562A7B37948BF6D6D54BC20068A353306F557573E76965332BE3A547CB500534C616869AD011E8E74A823A26C104CAC93F637AA526D2D1CB095E1875540653FB3E01E3ACF31ED89E3A021EDFB7561DE1CA9D111EA63E4A456730F18910116EDDB23C9AD5A166505647D31688491F5E4ED

b64encode(enc.encode('RSAPublicKey', {'modulus': x, 'publicExponent': 65537}))
```
This would result in:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/prateek/git/asn1tools/asn1tools/compiler.py", line 138, in encode
    return type_.encode(data, **kwargs)
  File "/home/prateek/git/asn1tools/asn1tools/codecs/ber.py", line 1448, in encode
    self._type.encode(data, encoded)
  File "/home/prateek/git/asn1tools/asn1tools/codecs/ber.py", line 535, in encode
    self.encode_member(member, data, encoded_members)
  File "/home/prateek/git/asn1tools/asn1tools/codecs/ber.py", line 571, in encode_member
    member.encode(value, encoded_members)
  File "/home/prateek/git/asn1tools/asn1tools/codecs/ber.py", line 750, in encode
    encoded.extend(encode_signed_integer(data))
  File "/home/prateek/git/asn1tools/asn1tools/codecs/ber.py", line 169, in encode_signed_integer
    encoded.append(len(encoded))
ValueError: byte must be in range(0, 256)
```

To fix that, I tried using a similar approach to encode as in `encode_length_definite(len)` in the `encode_signed_integer(data)` function.
```python
x = len(encoded)
if x > 127:
    length_bytes, l = bytearray(), x
    while l:
        length_bytes.append(l & 0xff)
        l >>= 8

    length_byte = 0x80 | len(length_bytes)
    encoded.extend(length_bytes)
    encoded.append(length_byte)
else: 
    encoded.append(x)
```

Let me know if you need some help in fixing this. I will try to re-use the `encode_length_definite` function to fix this. Similarly for the decode part as well.

**Comment by eerimoq** [comment]
Nice catch. Should be fixed in version 0.146.5!
