### ISSUE TITLE
encode error

### ISSUE THREAD

**Issue by CoderHuo** [eerimoq/asn1tools#65]
the asn file https://github.com/CoderHuo/learn-python3/blob/master/ulp204.asn

``` python
import asn1tools
import binascii

foo = asn1tools.compile_files('ulp204.asn', 'uper')

posTechnology = {
    'agpsSETassisted': {'agpsSETassisted': True, 'agpsSETBased': False, 'autonomousGPS': False, 'aflt': False,
                        'ecid': True, 'eotd': False, 'otdoa': False},
    'agpsSETBased': {'agpsSETassisted': False, 'agpsSETBased': True, 'autonomousGPS': False, 'aflt': False,
                     'ecid': True, 'eotd': False, 'otdoa': False}
}

posProtocol = {
    'rrlp': {
        'tia801': False,
        'rrlp': True,
        'rrc': False,
    },
    'lpp': {
        'tia801': False,
        'rrlp': False,
        'rrc': False,
    },
    'tia801': {
        'tia801': True,
        'rrlp': False,
        'rrc': False,
    },
    'rrc': {
        'tia801': False,
        'rrlp': False,
        'rrc': True,
    }
}
cellinfo = 'nrCell'
postechnology = posTechnology['agpsSETassisted']
posprotocol = posProtocol['lpp']

setId = ('imsi', b'd\x00\x00\x00\x00\x00 \xf2')
setSessionId = 65523
version = {'maj': 2, 'min': 0, 'servind': 4}

gsmCell = ('gsmCell', {'refMCC': 310, 'refMNC': 890, 'refLAC': 123, 'refCI': 234})

gsmCellNmr = (
    'gsmCell', {
        'refMCC': 310, 'refMNC': 300, 'refLAC': 2260, 'refCI': 16062,
        'nMR': [{'aRFCN': 721, 'bSIC': 18, 'rxLev': 32}],
        'tA': 0
    }
)

wcdmaCell = ('wcdmaCell', {'refMCC': 310, 'refMNC': 890, 'refUC': 234})

cdmaCell = (
    'cdmaCell', {
        'refNID': 23, 'refSID': 112, 'refBASEID': 12345, 'refBASELAT': 0,
        'reBASELONG': 0, 'refREFPN': 0, 'refWeekNumber': 0, 'refSeconds': 0
    }
)

lteCell = (
    'ver2-CellInfo-extension', (
        'lteCell', {
            'cellGlobalIdEUTRA': {
                'plmn-Identity': {'mcc': [3, 1, 0], 'mnc': [3, 1, 0]},
                'cellIdentity': (b'4\xa3  ', 28)
            },
            'physCellId': 304,
            'trackingAreaCode': (b'\x13\x8e', 16),
            'rsrpResult': 70,
            'rsrqResult': 24,
            'tA': 1,
            'measResultListEUTRA': [{'physCellId': 275, 'measResult': {'rsrpResult': 56, 'rsrqResult': 9}}]
        }
    )
)

nrCell = (
    'ver2-CellInfo-extension', (
        'nrCell', {
            'servingCellInformation': [
                {'physCellId': 100, 'arfcn-NR': 100,
                 'cellGlobalId': {'plmn-Identity': {'mcc': [3, 1, 0], 'mnc': [3, 1, 0]},
                                  'cellIdentityNR': (b'4\xa3  ', 28)},
                 'trackingAreaCode': (b'\x13\x8e', 16),
                 'ssb-Measurements': {'rsrp-Range': 1, 'rsrq-Range': 2, 'sinr-Range': 3},
                 'csi-rs-Measurements': {'rsrp-Range': 1, 'rsrq-Range': 2, 'sinr-Range': 3},
                 'ta': 100}],
            'measuredResultsListNR': [
                {'physCellId': 100, 'arfcn-NR': 100,
                 'cellGlobalId': {'plmn-Identity': {'mcc': [3, 1, 0], 'mnc': [3, 1, 0]},
                                  'cellIdentityNR': (b'4\xa3  ', 28)},
                 'trackingAreaCode': (b'\x13\x8e', 16),
                 'ssb-Measurements': {'rsrp-Range': 1, 'rsrq-Range': 2, 'sinr-Range': 3},
                 'csi-rs-Measurements': {'rsrp-Range': 1, 'rsrq-Range': 2, 'sinr-Range': 3}}]
        }
    )
)

locationId = {
    'gsmCell': {'cellInfo': gsmCell, 'status': 'stale'},
    'gsmCellNmr': {'cellInfo': gsmCellNmr, 'status': 'stale'},
    'wcdmaCell': {'cellInfo': wcdmaCell, 'status': 'stale'},
    'cdmaCell': {'cellInfo': cdmaCell, 'status': 'stale'},
    'lteCell': {'cellInfo': lteCell, 'status': 'stale'},
    'nrCell': {'cellInfo': nrCell, 'status': 'stale'}
}

msSUPLSTART = {
    'length': 0,
    'version': version,
    'sessionID': {'setSessionID': {'sessionId': setSessionId, 'setId': setId}},
    'message': (
        'msSUPLSTART', {
            'sETCapabilities': {
                'posTechnology': postechnology,
                'prefMethod': 'noPreference',
                'posProtocol': posprotocol
            },
            'locationId': locationId[cellinfo],
            'qoP': {'horacc': 26, 'maxLocAge': 0, 'delay': 7},
            # 'ver2-SUPL-START-extension': ver2SUPLPOSINITextension[cellinfo]
        }
    )
}

encoded = foo.encode('ULP-PDU', msSUPLSTART)
print(encoded)
print(binascii.hexlify(encoded))
print(foo.decode('ULP-PDU', encoded))
```

error :

```
"C:\Program Files (x86)\Python37-32\python.exe" C:/Users/shhuo/PycharmProjects/cLBS/uuid_test.py
Traceback (most recent call last):
  File "C:/Users/shhuo/PycharmProjects/cLBS/uuid_test.py", line 132, in <module>
bytearray(b'\x00\x00\x02\x00\x04\xbf\xfc\xcd\x90\x00\x00\x00\x00\x00\x83\xc8R$\x08\x02\xd8\x02\xb4\x0e2\x00\x00\xc8\x98\x84\xc4\r(\xc8\x08N9\xc0\x82\x06\xe0A\x03\x06@<d\x00\x01\x911\t\x88\x1aQ\x90\x10\x9cs\x81\x04\r\xc0\x82\x06\x00f\x80\x008')
b'0000020004bffccd90000000000083c852240802d802b40e320000c89884c40d28c8084e39c08206e0410306403c640001913109881a5190109c7381040dc082060066800038'
0
    print(foo.decode('ULP-PDU',encoded))
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\asn1tools\compiler.py", line 163, in decode
    decoded = type_.decode(data)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\asn1tools\codecs\uper.py", line 462, in decode
    return self._type.decode(decoder)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\asn1tools\codecs\per.py", line 817, in decode
    decoded = self.decode_root(decoder)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\asn1tools\codecs\per.py", line 831, in decode_root
    value = member.decode(decoder)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\asn1tools\codecs\per.py", line 1634, in decode
    return self.decode_root(decoder)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\asn1tools\codecs\per.py", line 1652, in decode_root
    return (member.name, member.decode(decoder))
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\asn1tools\codecs\per.py", line 815, in decode
    decoded = self.decode_root(decoder)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\asn1tools\codecs\per.py", line 831, in decode_root
    value = member.decode(decoder)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\asn1tools\codecs\per.py", line 815, in decode
    decoded = self.decode_root(decoder)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\asn1tools\codecs\per.py", line 831, in decode_root
    value = member.decode(decoder)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\asn1tools\codecs\per.py", line 1632, in decode
    return self.decode_additions(decoder)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\asn1tools\codecs\per.py", line 1688, in decode_additions
    decoded = addition.decode(decoder)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\asn1tools\codecs\per.py", line 1632, in decode
    return self.decode_additions(decoder)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\asn1tools\codecs\per.py", line 1688, in decode_additions
    decoded = addition.decode(decoder)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\asn1tools\codecs\per.py", line 815, in decode
    decoded = self.decode_root(decoder)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\asn1tools\codecs\per.py", line 831, in decode_root
    value = member.decode(decoder)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\asn1tools\codecs\uper.py", line 158, in decode
    decoded_element = self.element_type.decode(decoder)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\asn1tools\codecs\per.py", line 815, in decode
    decoded = self.decode_root(decoder)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\asn1tools\codecs\per.py", line 831, in decode_root
    value = member.decode(decoder)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\asn1tools\codecs\per.py", line 813, in decode
    decoded.update(self.decode_additions(decoder))
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\asn1tools\codecs\per.py", line 866, in decode_additions
    decoder.skip_bits(8 * open_type_length)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\asn1tools\codecs\per.py", line 375, in skip_bits
    raise OutOfDataError(self.number_of_read_bits())
asn1tools.codecs.OutOfDataError: message: locationId: cellInfo: servingCellInformation: ssb-Measurements: out of data at bit offset 351 (43.7 bytes)
```

**Comment by eerimoq** [comment]
TrackingAreaCodeNR and CellIdentityNR BIT STRING:s have the wrong length in the encode input. ASN.1 schema says 36 and 24, not 28 and 16 as given as input to the encode function.

The encode function should be improved to fail in these cases to help the user.

**Comment by CoderHuo** [comment]
sorry . Thanks.
