### ISSUE TITLE
encoding CHOICE of CHOICE with OER

### ISSUE THREAD

**Issue by johughes99** [eerimoq/asn1tools#66]
I’m trying to create a message according to the below ASN.1 schema – such that I have a EccP256CurvePoint with incompresssedP256 x and y points using OER

However, I can’t seem to get it to work. Obviously I’m not providing the correct string into the “data” parameter. I have tried all sort of options and normally I get the unhashble in dict error
Can someone provide an example of string I should pass into the .encode method? I understand the various on-line examples – but nothing shows an example where you have a CHOICE of CHOICE of CHOICE and then the SEQUENCE

John

EccP256CurvePoint DEFINITIONS ::= BEGIN

PublicVerificationKey ::= CHOICE  { 
    ecdsaNistP256             EccP256CurvePoint,
    ecdsaBrainpoolP256r1      EccP256CurvePoint,
    ...,
    ecdsaBrainpoolP384r1      EccP384CurvePoint
}

EccP256CurvePoint ::= CHOICE  {
    x-only           OCTET STRING (SIZE (32)),
    fill             NULL,  -- consistency with 1363 / X9.62
    compressed-y-0   OCTET STRING (SIZE (32)),
    compressed-y-1   OCTET STRING (SIZE (32)),
    uncompressedP256 SEQUENCE  {
        x OCTET STRING (SIZE (32)),
        y OCTET STRING (SIZE (32))
    }
}

EccP384CurvePoint::= CHOICE  {
    x-only           OCTET STRING (SIZE (48)),
    fill             NULL, -- consistency w 1363 / X9.62
    compressed-y-0   OCTET STRING (SIZE (48)),
    compressed-y-1   OCTET STRING (SIZE (48)),
    uncompressedP384 SEQUENCE  {
        x OCTET STRING (SIZE (48)),
        y OCTET STRING (SIZE (48))
    }
}

END

**Comment by eerimoq** [comment]
Looks like a bug in asn1tools. The script below can be used to reproduce it.

``` python
import asn1tools

SPEC = '''
EccP256CurvePoint DEFINITIONS ::= BEGIN

PublicVerificationKey ::= CHOICE  { 
    ecdsaNistP256             EccP256CurvePoint,
    ecdsaBrainpoolP256r1      EccP256CurvePoint,
    ...,
    ecdsaBrainpoolP384r1      EccP384CurvePoint
}

EccP256CurvePoint ::= CHOICE  {
    x-only           OCTET STRING (SIZE (32)),
    fill             NULL,  -- consistency with 1363 / X9.62
    compressed-y-0   OCTET STRING (SIZE (32)),
    compressed-y-1   OCTET STRING (SIZE (32)),
    uncompressedP256 SEQUENCE  {
        x OCTET STRING (SIZE (32)),
        y OCTET STRING (SIZE (32))
    }
}

EccP384CurvePoint::= CHOICE  {
    x-only           OCTET STRING (SIZE (48)),
    fill             NULL, -- consistency w 1363 / X9.62
    compressed-y-0   OCTET STRING (SIZE (48)),
    compressed-y-1   OCTET STRING (SIZE (48)),
    uncompressedP384 SEQUENCE  {
        x OCTET STRING (SIZE (48)),
        y OCTET STRING (SIZE (48))
    }
}

END
'''

decoded = (
    'ecdsaNistP256',
    (
        'uncompressedP256',
        {
            'x': 32 * b'\x12',
            'y': 32 * b'\x34'
        }
    )
)

print('UPER:')
spec = asn1tools.compile_string(SPEC, 'uper')
print(spec.encode('PublicVerificationKey', decoded))

print('OER:')
spec = asn1tools.compile_string(SPEC, 'oer')
print(spec.encode('PublicVerificationKey', decoded))
```

The output:

```
python3 test.py
UPER:
bytearray(b' \x90\x90\x90\x90\x90\x90\x90\x90\x90\x90\x90\x90\x90\x90\x90\x90\x90\x90\x90\x90\x90\x90\x90\x90\x90\x90\x90\x90\x90\x90\x90\x91\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa1\xa0')
OER:
Traceback (most recent call last):
  File "test.py", line 55, in <module>
    print(spec.encode('PublicVerificationKey', decoded))
  File "/usr/local/lib/python3.7/dist-packages/asn1tools/compiler.py", line 138, in encode
    return type_.encode(data, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/asn1tools/codecs/oer.py", line 1299, in encode
    self._type.encode(data, encoder)
  File "/usr/local/lib/python3.7/dist-packages/asn1tools/codecs/oer.py", line 996, in encode
    encoder.append_bytes(member.tag)
  File "/usr/local/lib/python3.7/dist-packages/asn1tools/codecs/oer.py", line 100, in append_bytes
    self.append_bits(data, 8 * len(data))
TypeError: object of type 'NoneType' has no len()

Compilation exited abnormally with code 1 at Sat Nov  2 17:44:19
```

**Comment by johughes99** [comment]
Many thanks.  Very useful - although it would be nice for it to fixed at some point:-)

**Comment by eerimoq** [comment]
Yeah =)

I'm working on other projects atm, but might have a look eventually.

**Comment by eerimoq** [comment]
Implemented a test to reproduce the error: https://github.com/eerimoq/asn1tools/blob/master/tests/test_oer.py#L508-L527
