### ISSUE TITLE
Accessing constants by name when assigning field values

### ISSUE THREAD

**Issue by olegst90** [eerimoq/asn1tools#8]
Hello!
I have such a question.
I have a module:
```
Foo DEFINITIONS ::= BEGIN
    defID0 INTEGER ::= 0
    defID1 INTEGER ::= 1
    IDType ::= INTEGER (defID0 | defID1)
    Answer ::= SEQUENCE {
        id        IDType,
        answer    BOOLEAN
    }

END
```

and I try to create an instance of Answer and assign id field a constant value:
`tmf.encode("Answer",{'id':'defID0','answer':1})`
and I get such an error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/asn1tools/compiler.py", line 75, in encode
    return self._types[name].encode(data)
  File "/usr/local/lib/python2.7/dist-packages/asn1tools/codecs/der.py", line 953, in encode
    self._type.encode(data, encoded)
  File "/usr/local/lib/python2.7/dist-packages/asn1tools/codecs/der.py", line 325, in encode
    member.encode(value, encoded_members)
  File "/usr/local/lib/python2.7/dist-packages/asn1tools/codecs/der.py", line 198, in encode
    encoded.extend(encode_signed_integer(data))
  File "/usr/local/lib/python2.7/dist-packages/asn1tools/codecs/der.py", line 120, in encode_signed_integer
    encoded.append(data & 0xff)
TypeError: unsupported operand type(s) for &: 'str' and 'int'
```

Is it possible to use constants defined in my module to assign field values?

Thank you in advance.

PS In my test, I was using DER encoder

**Comment by eerimoq** [comment]
Hello,

no, only the Python type "int" is supported for the INTEGER type. asn1tools does not use defined values at all in the current implementation. It does not even check constraints. It could possibly be added, but it would add some overhead in the encode and decode functions, so it's a tradeoff performance vs user friendliness. There are no plans to support defined constants as input to encode/output from decode for now.

**Comment by olegst90** [comment]
Ok, thank you for reply.
